CREATE TABLE IF NOT EXISTS `mydb`.`BASIC_ENTITY` (
  `ID` MEDIUMTEXT NOT NULL,
  `STRING_VALUE` VARCHAR(45) NULL,
  `DATE_VALUE` DATETIME NULL,
  `BOOLEAN_VALUE` TINYINT(1) NULL,
  `CURRENCY_VALUE` VARCHAR(45) NULL,
  `ENUM_VALUE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB